CREATE USER CRMSCH IDENTIFIED BY CRMSCH;

GRANT ALL PRIVILEGES ON * . * TO CRMSCH;

GRANT CONNECT TO CRMSCH;
GRANT CONNECT, RESOURCE, DBA TO CRMSCH;
GRANT CREATE SESSION TO CRMSCH;

GRANT SELECT, INSERT, UPDATE, DELETE ON CRMSCH.CUSTOMER TO CRMSCH;




