CREATE USER SPRINGSTUDENT IDENTIFIED BY SPRINGSTUDENT;

GRANT ALL PRIVILEGES ON * . * TO SPRINGSTUDENT;

GRANT CONNECT TO SPRINGSTUDENT;
GRANT CONNECT, RESOURCE, DBA TO SPRINGSTUDENT;
GRANT CREATE SESSION TO SPRINGSTUDENT;

GRANT SELECT, INSERT, UPDATE, DELETE ON SPRINGSTUDENT.CUSTOMER TO SPRINGSTUDENT;




